const products1 = [
  {
    img: "img/products/f1.jpg",
    brand: "adidas",
    name: " Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 58,
    id: 1,
  },

  {
    img: "img/products/f2.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 20,
    id: 2,
  },

  {
    img: "img/products/f3.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 30,
    id: 3,
  },
  {
    img: "img/products/f4.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 40,
    id: 4,
  },
  {
    img: "img/products/f5.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 50,
    id: 5,
  },
  {
    img: "img/products/f6.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 60,
    id: 6,
  },
  {
    img: "img/products/f7.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 70,
    id: 7,
  },
  {
    img: "img/products/f8.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 80,
    id: 8,
  },
  {
    img: "img/products/n1.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 90,
    id: 9,
  },
  {
    img: "img/products/n2.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 10,
    id: 10,
  },
  {
    img: "img/products/n3.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 20,
    id: 11,
  },
  {
    img: "img/products/n4.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 30,
    id: 12,
  },
  {
    img: "img/products/n5.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 40,
    id: 13,
  },
  {
    img: "img/products/n6.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 15,
    id: 14,
  },
  {
    img: "img/products/n7.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 35,
    id: 15,
  },
  {
    img: "img/products/n8.jpg",
    brand: "adidas",
    name: "Cartoon Austronaut T-shirts",
    stars: 5,
    priceCents: 25,
    id: 16,
  },
];
